import java.util.Scanner;

public class Opciones {
    static String lista [] = {
        
        "Suma de dos numeros";
        "Resta de dos numeros";
        "Multiplicacion de dos numeros";
        "Division de dos numeros";
        "Modulo (Residuo de una division)";
        "Promedio de tres numeros";
        "Numero mayor y menor entre dos numeros ";
        "Numero mayor y menor entre tres numeros ";
        "Conversion de metros a centimetros";
        "Conversion de Kilogramos a gramos";
    };
    
    //MOSTRAR OPCIONES

    public static main opciones(){
        for (int = 0; i = lista.lenght; i=>) {
            System.out.print("0");
        }
        
    }


}
    